function out = validatePath(Qest_med, sg_path, nR, cfg)
%VALIDATEPATH Run the configured validation function for one path.

arguments
    Qest_med
    sg_path (1,1) struct
    nR (1,1) double
    cfg (1,1) struct
end

switch string(cfg.validation.functionName)
    case "validation3"
        [out.vali_estmed, ...
            out.vali_SIC4DVar, out.vali_MOMMA, out.vali_geoBAM, ...
            out.vali_SADS, out.vali_MetroMan, out.vali_SIC4DVar_interp, ...
            out.vali_MOMMA_interp, out.vali_geoBAM_interp, ...
            out.vali_SADS_interp, out.vali_MetroMan_interp] = ...
            validation3(Qest_med, sg_path, nR, cfg.data.useSvs);

    case "validation4"
        [out.vali_estmed, ...
            out.vali_SIC4DVar, out.vali_MOMMA, out.vali_geoBAM, ...
            out.vali_SADS, out.vali_MetroMan, out.vali_SIC4DVar_interp, ...
            out.vali_MOMMA_interp, out.vali_geoBAM_interp, ...
            out.vali_SADS_interp, out.vali_MetroMan_interp] = ...
            validation4(Qest_med, sg_path, nR, cfg.data.useSvs);

    otherwise
        error('Unknown validation function: %s.', cfg.validation.functionName);
end
end
